/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class KeygenSession {
  static create(keys: KeygenPartyKeys, t: number, n: number, pid: number, rank: number, ephemeral: boolean): KeygenSession
  errorMsg(): string | null
  status(): number
  processMessages(msg: Buffer): Promise<Buffer>
  finalize(): Keyshare
}
export class SignSession {
  static create(share: Keyshare, msg: Buffer): SignSession
  initMessage(): Buffer
  errorMsg(): string | null
  status(): number
  processMessages(msg: Buffer): Promise<Buffer>
  finalize(): Buffer
}
export class KeygenPartyKeys {
  static create(): Promise<KeygenPartyKeys>
  static fromBytes(bytes: Buffer): KeygenPartyKeys
  toBytes(): Buffer
  publicKeys(): Buffer
}
export class Keyshare {
  static fromBytes(bytes: Buffer): Keyshare
  toBytes(): Buffer
  participantId(): number
  participants(): number
  threshold(): number
}
