name: Rust Example
on:
  push:
    branches:
      - core-after-audit

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/dkls-metrics/benches
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run:  cargo +nightly bench | tee output.txt

      - name: Create benchmarks
        uses: benchmark-action/github-action-benchmark@v1.20.4
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: ./crates/dkls-metrics/benches/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
