name: Rust Example
on:
  push:
    branches:
      - core-after-audit
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'crates/**'
      - '.github/**'
  pull_request:
    branches:
      - core-after-audit
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'crates/**'
      - '.github/**'

permissions:
  contents: write
  deployments: write

jobs:
  get_benchmark:
    name: Run Benchmarks
    runs-on: github-builder

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run:  cd crates/dkls-metrics/benches && cargo +nightly bench -- --output-format bencher > /tmp/output.txt
      - name: Create benchmarks
        uses: benchmark-action/github-action-benchmark@v1.20.4
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: /tmp/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: docs
          auto-push: true
          comment-on-alert: true
          summary-always: true

  make_the_html_page:
    runs-on: github-builder
    name: Create html page
    needs: get_benchmark

    steps:
      - name: Checkout code (main)
        uses: actions/checkout@v4
        with:
          ref: core-after-audit
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.85
        with:
          toolchain: 1.85
      - name: Write the html page
        run: |
          python -m pip install --upgrade pip
          python scripts/process_benchmarks_to_html.py gh-pages/docs/data.js
          cargo doc --no-deps 
          mkdir -p docs
          mkdir -p docs/rustdocs
          cp scripts/sil.jpg docs
          mv gh-pages/* docs 
          mv index.html docs
          mv target/doc/* docs/rustdocs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
