name: Rust Example
on:
  push:
    branches:
      - core-after-audit

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run:  cd crates/dkls-metrics/benches && cargo +nightly bench -- --output-format bencher > /tmp/output.txt
      - name: Create benchmarks
        uses: benchmark-action/github-action-benchmark@v1.20.4
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: /tmp/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: docs
          auto-push: true
          comment-on-alert: true
          summary-always: true
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (main)
        uses: actions/checkout@v4
        with:
          ref: core-after-audit # Ensure we are on the 'main' branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages # Checkout the gh-pages branch to a separate directory
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 # Or any version you need
      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
      - name: Run the script
        run: python scripts/process_benchmarks_to_html.py gh-pages/docs/data.js # Execute your Python script with the correct path
      - name: Create the docs directory
        run: mkdir -p docs # create the docs folder
      - name: Move output
        run: mv index.html docs/ # Move the generated HTML to the docs folder
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch to deploy to
          folder: docs # The folder containing the generated content
